config/routes.rb
Peerreview::Application.routes.draw do
  get "welcome/index"
  resources :reviews

  resources :answers

  resources :questions

  resources :teams

  resource :review do
    get 'fill_out_review', :on => :collection
  end

  root :to => 'welcome#index'

  post '/auth/admin/callback' => 'welcome#start'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	#TODO Why? shouldnt this just be for a POST request
  protect_from_forgery :except => :start 
  
  def index
  end
  
  def start
    email = env['omniauth.auth']['info']['email']
    p 'Found ' + email
    session[:user_id] = email
    user = User.where('email = ?', session[:user_id]).first
    session[:user_admin] = !user.nil? && user.admin
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<br>

<div class="hero-unit">
  <h1>The PeerReviewApp</h1>
  <p> Your rules. Your Peers. </p>

  <p><%= link_to 'Login', '/auth/admin', class: 'btn btn-primary btn-large' %></p>

</div>

app/views/welcome/start.html.erb
<br>

<div class="hero-unit">
  <img src="/assets/splash.png" class="splash" />
  <h2> Hallo Kollege,</h2> 
  <p>schön, dass Du Dir die Zeit nimmst, Deinen Kollegen ein strukturiertes Feedback zu geben. Neben dem alltäglichen (unersetzbaren) “Miteinander Reden” sollen an dieser Stelle die Faktoren Produktivität, Quälität, MVP, technische Excellenz, unternehmerische Weitsicht, Zusammenarbeit, Wissenstransfer und Dev/Scrum Orga betrachtet werden.</p>
  
<p>Damit die Peer Review funktioniert, beachte bitte Folgendes: </p>
<ol>
	<li> Wähle Deine Rolle aus, dann bekommst Du auch die richtigen Fragen </li>
	<li> Bitte plance ca. eine halbe Stunde zur Beantwortung ein. Schneller klappt es nicht. </li>
	<li> Jeder Jeck ist anders! Daher mache Dir bitte Gedanken über jeden einzelnen Deiner Kollegen. Ganz wichtig: Es ist nicht gewollt, dass Du im Feedbackprozess ein Ranking erstellst! </li>
	<li> Ehrlichkeit währt am längsten </li>
<li> Dieses Tool ist in der Hauptsache für Dich. Wenn irgendetwas nicht stimmt, Dir komisch vorkommt oder Dir nicht passt, bitte gib Feedback zum Feedback und kläre alle Unklarheiten. </li>
</ol>


<p>Weitere Infos gibt es im <a href="https://wiki.adcloud.com/display/DEV/PeerReview+App"> Wiki </a> </p>

<p>Vielen Dank!</p>

<p>
  	<%= link_to 'Start PeerReview', new_review_path, class: 'btn btn-primary btn-large' %>
</p>
</p>
</div>